### ISSUE TITLE
Upgrade to a newer version of VS from VS 2008

### ISSUE THREAD

**Issue by lgoffin** [SasanTV/Celeris#1]
Hi,
I was trying to compile Celeris on a Windows 10 machine with the Intel compiler and VS 2013. It looks like D3DX* is not supported anymore on latest DirectX SDK versions (https://blogs.msdn.microsoft.com/chuckw/2012/05/07/hlsl-fxc-and-d3dcompile/).
What are your compilation specifications ?
When I try with DirectX SDK (June 2010 version), it finds D3DX*, however i get an error due to fxc.exe. Do you have any idea where I have to look at for solving this ?
Louis

**Comment by SasanTV** [comment]
Hi Louis,
I am glad that you are interested in Celeris. I am using VS-2008 to compile Celeris! Last year I tried to port the project and compile it with VS-2012, but it just didn't work and I gave up after a few days. Celeris is based on an earlier open source code (http://www.solarflare.org.uk/shallow_water/), and the first developer has used some of his own wrappers for D3X, and I kept using them. 
I recommend you to compile each project separately first, and make sure which project is not compatible. Then you must compile in the debug mode to find the problem. 
Sticking to VS-2008 is a drawback for Celeris, and if you can compile it in a newer version of VS, it would be a great step forward.

Sasan

**Comment by lgoffin** [comment]
Hi Sasan,
Thanks you for your quick reply. I will try your suggestions asap and let you know about whether I succeed or not in compiling the solution with VS2013.
Louis

**Comment by SasanTV** [comment]
Hi Louis, 

I was wondering if you had any progress with recompiling Celeris with a newer version of VS.

Sasan

**Comment by lgoffin** [comment]
Hi Sasan,

I couldn’t manage to compile Celris with a newer version of VS. I hadn’t much time either to make new attempts. I’ll let you know about outcomes if I have some.

Louis.

**Comment by yf1412** [comment]
@SasanTV 
Hi Saan,

I have already compile the Celeris with the VS2017. And it sounds well.

**Comment by SasanTV** [comment]
Hi There, 

It would be wondeful if you fork and upload it here.

Sasan

**Comment by SasanTV** [comment]
I successfully compiled Celeris with VS 2017 Community version, and will push it to GitHub with the next release of Celeris. 

Closing this issue :)

~Sasan
