### ISSUE TITLE
Run on macOS and Linux

### ISSUE THREAD

**Issue by martincolladodotcom** [SasanTV/Celeris#2]
Would be possible to compile this project into macOS and Linux OS? Or is exclusive for Windows environments? Thank you very much for this project!

**Comment by SasanTV** [comment]
Thanks for your interest in Celeris. Celeris uses DirectX 11, and therefore it only runs on Windows. However, it might be possible to run it on Linux (or even on Mac) using third party solutions such as Wine, or virtual machine. I have never tried it myself, please let us know you succeeded running Celeris on any OS other than Windows. Think of Celeris as a Windows game, if you find a way to run a high end Windows game on Linux, the same would probably work for Celeris. 

Finally, I don't think you need to recompile Celeris to try any of the possible solutions.

**Comment by martincolladodotcom** [comment]
Hello, first at all really sorry for the delay on my reply.Finally was not necessary to run on a different system.But I've tested on virtual machines on Linux and macos systems and works fine.

I have been using it for the past few months and I really enjoy it this software!!.I am experiencing some issues with a thing that I'm working on in, but I'll create a new issue soon to discuss there about it.Thanks.
